apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-db-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysql-credentials
    template:
      engineVersion: v2
      data: 
        credentials: |
          db_con="{{ .db_url }}"
          db_user="{{ .db_username }}"
          db_password="{{ .db_password }}"
        
  data:
  - secretKey: db_url
    remoteRef:
      key: mysql_credentials
      property: url
  - secretKey: db_username
    remoteRef:
      key: mysql_credentials
      property: username
  - secretKey: db_password
    remoteRef:
      key: mysql_credentials
      property: password   
    