apiVersion: v1
kind: Service
metadata:
  name: gitops-secrets-service
spec:
  type: ClusterIP
  selector:
    app: gitops-secrets-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080